apiVersion: v1
kind: Namespace
metadata:
  name: redis

---

apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:latest
    ports:
    - containerPort: 6379
    resources:
      limits:
        memory: "2Gi"

---

kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: redis
spec:
  selector:
    app: redis
  ports:
  # Default port used by the image
  - port: 6379
